project: kicksware
component: gitlab-ci
nameOverride: ""
fullnameOverride: ""
deployment:
  replicaCount: 1

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    # Gitlab CI web app
    - host: ci.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: gitlab-ci-webservice
          port: 8181
          scheme: http
    # Gitlab CI Sidekiq web app
    - host: ci.adm.kicksware.com
      paths:
        - /
      middlewares: [ ]
      services:
        - name: gitlab-ci-webservice
          port: 8080
          scheme: http
        - name: gitlab-ci-webservice
          port: 8181
          scheme: http
    # Gitlab CI registry service
    - host: registry.kicksware.com
      paths:
        - /
      middlewares: [ ]
      services:
        - name: gitlab-ci-registry
          port: 5000
          scheme: http
    # Gitlab CI minio service
    - host: minio.kicksware.com
      paths:
        - /
      middlewares: [ ]
      services:
        - name: gitlab-ci-minio-svc
          port: 9000
          scheme: http

environment: {}

resources: {}

serviceAccount:
  create: true
  name: ""