include: /.gitlab/.gitlab-ci.compose.yml

image: dtzar/helm-kubectl:3.3.0

stages:
  - deploy

# deploy stage steps:

mongodb.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - mongodb/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  before_script:
    - kubectl create secret generic mongo-auth -n toolstack --dry-run --from-literal=MONGO_USER=$MONGO_USER --from-literal=MONGO_PASSWORD=$MONGO_PASSWORD -o yaml | kubectl apply -f -
  script:
    - helm upgrade --install -n toolstack mongodb mongodb/

elasticsearch.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - elasticsearch/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm upgrade --install -n toolstack elasticsearch elasticsearch/

kibana.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - kibana/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm upgrade --install -n toolstack kibana kibana/

elasticstack.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - elasticstack/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add elastic https://helm.elastic.co
    - helm repo update
    # - helm upgrade --install -n toolstack logstash elastic/logstash -f=elasticstack/logstash.yaml
    - helm upgrade --install -n toolstack filebeat elastic/filebeat -f=elasticstack/filebeat.yaml
    - helm upgrade --install -n toolstack metricbeat elastic/metricbeat -f=elasticstack/metricbeat.yaml
    # - helm upgrade --install apm-server elastic/apm-server -f=elasticstack/apm-server.yaml

gitlab-ci.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-ce/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io/
    - helm repo update
    - helm upgrade --install -n gitlab gitlab-ci gitlab/gitlab -f=gitlab-ci/gitlab-ce/values.yaml

gitlab-runner.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-runner/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io
    - helm repo update
    - helm upgrade --install -n gitlab gitlab-ci gitlab/gitlab-runner -f=gitlab-ci/gitlab-runner/values.yaml

gitlab-addons.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-addons/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm upgrade --install -n gitlab gitlab-ci-addons gitlab-ci/gitlab-addons/
