include: /compose/.gitlab-ci.yml

image: dtzar/helm-kubectl:3.3.0

stages:
  - deploy

variables:
  SOURCE_DIR: /source/repos/$CI_PROJECT_NAME

# deploy stage steps:

deploy.mongodb:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - mongodb/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  before_script:
    - kubectl create secret generic mongo-auth -n=toolstack --dry-run --from-literal=MONGO_USER=${MONGO_USER} --from-literal=MONGO_PASSWORD=${MONGO_PASSWORD} -o yaml | kubectl apply -f -
  script:
    -  helm upgrade --install -n toolstack mongodb mongodb/

deploy.elasticsearch:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - elasticsearch/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    -  helm upgrade --install -n toolstack elasticsearch elasticsearch/

deploy-kibana-step:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - kibana/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    -  helm upgrade --install -n toolstack kibana kibana/

deploy.filebeat:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - filebeat/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    -  helm upgrade --install -n toolstack filebeat filebeat/

deploy.gitlab-ci:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-ce/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io/
    - helm repo update
    - helm upgrade --install -n gitlab gitlab-ci gitlab/gitlab -f=gitlab-ci/gitlab-ce/values.yaml

deploy.gitlab-runner:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-runner/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io
    - helm repo update
    - helm upgrade --install -n gitlab gitlab-ci gitlab/gitlab-runner -f=gitlab-ci/gitlab-runner/values.yaml

deploy.gitlab-addons:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-addons/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm upgrade --install -n gitlab gitlab-ci-addons gitlab-ci/gitlab-addons/
