include: /compose/.gitlab-ci.yml

image: alpine/helm:3.3.0

stages:
  - deploy

variables:
  SOURCE_DIR: /source/repos/$CI_PROJECT_NAME

# deploy stage steps:

deploy.mongodb:
  stage: deploy
  tags:
    - k8s
    - tool-stack
#  only:
#    changes:
#      - mongodb/**/*
#    kubernetes: active
#  except:
#    changes:
#      - "*.md"
  script:
    - helm init
    - helm upgrade --install mongodb mongodb/

deploy.elasticsearch:
  stage: deploy
  tags:
    - k8s
    - tool-stack
#  only:
#    changes:
#      - elasticsearch/**/*
#    kubernetes: active
#  except:
#    changes:
#      - "*.md"
  script:
    -  helm upgrade --install elasticsearch elasticsearch/

deploy-kibana-step:
  stage: deploy
  tags:
    - k8s
    - tool-stack
#  only:
#    changes:
#      - kibana/**/*
#    kubernetes: active
#  except:
#    changes:
#      - "*.md"
  script:
    -  helm upgrade --install kibana kibana/

deploy.filebeat:
  stage: deploy
  tags:
    - k8s
    - tool-stack
#  only:
#    changes:
#      - filebeat/**/*
#    kubernetes: active
#  except:
#    changes:
#      - "*.md"
  script:
    -  helm upgrade --install filebeat filebeat/

deploy.gitlab-ci:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-ce/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io/
    - helm repo update
    - helm upgrade --install gitlab-ci gitlab/gitlab -f=gitlab-ci/gitlab-ce/values.yaml

deploy.gitlab-runner:
  stage: deploy
  tags:
    - k8s
    - tool-stack
  only:
    changes:
      - gitlab-ci/gitlab-runner/**/*
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm repo add gitlab https://charts.gitlab.io
    - helm repo update
    - helm upgrade --install gitlab-ci gitlab/gitlab-runner -f=gitlab-runner/gitlab-ce/values.yaml

deploy.gitlab-addons:
  stage: deploy
  tags:
    - k8s
    - tool-stack
#  only:
#    changes:
#      - gitlab-ci/gitlab-addons/**/*
#    kubernetes: active
#  except:
#    changes:
#      - "*.md"
  script:
    - helm upgrade --install gitlab-ci-addons gitlab-ci/gitlab-addons/
