apiVersion: apps/v1
{{- if .Values.deployment.stateful}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: mongodb
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  {{- if .Values.deployment.stateful}}
  updateStrategy:
    type: RollingUpdate
  {{- else }}
  strategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.deployment.stateful}}
  serviceName: mongodb-6c3816ec85f85dafe
  {{- end }}
  template:
    metadata:
      labels:
    {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: {{ .Values.service.port }}
          env: []
          command:
            - mongod
          args:
            - --dbpath=/data/db
            - --port={{ .Values.service.port }}
            - --bind_ip=0.0.0.0
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: tls
              mountPath: /certs
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tls
          secret:
            secretName: mongo-tls
        {{- if .Values.storage.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "chart.fullname" .}}.claim
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}

