{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "chart.fullname" . }}{{- if .Values.ingress.tls.enabled }}.secure{{- end }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entrypoints | nindent 4 }}
  routes:
  {{- range .Values.ingress.routes }}
    - match: HostSNI(`{{ .host }}`)
      kind: Rule
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    passthrough: {{ .Values.ingress.tls.passthrough }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}