apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}
