project: kicksware
component: kibana
nameOverride: ""
fullnameOverride: ""
baseDirL: &baseDir /run/desktop/mnt/host/wsl

elasticsearchHost: http://elasticsearch:9200

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

deployment:
  replicaCount: 1

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: analytics.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: kibana
          port: 5601
          scheme: http

volumes: {}

environment: {}

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"

serviceAccount:
  create: true
  name: ""
