apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.elasticsearchHost }}
            - name: ELASTICSEARCH_URL
              value: {{ .Values.elasticsearchHost }}
            - name: SERVER_HOST
              value: 0.0.0.0
          volumeMounts:
            - name: config
              mountPath: /usr/share/kibana/config
            {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /app/kibana
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- with .host }}
          hostPath:
            path: {{ .pathBase }}{{ .path }}
            type: {{ .type }}
          {{- end }}
          {{- with .persistent }}
          persistentVolumeClaim:
            claimName: {{ .claim }}
          {{- end }}
        {{- end }}
        - name: config
          configMap:
            name: {{ template "chart.fullname" . }}.config

