---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            matchers:
            - logs_path:
                logs_path: /var/log/containers/
    output.elasticsearch:
      hosts: [{{ .Values.elasticsearch.host }}]
    setup.kibana:
      host: {{ .Values.kibana.host }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.modules
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  traefik.yml: |-
    - module: traefik
      access:
        enabled: true
        var.paths:
          {{- toYaml .Values.modules.traefik.accessLogPaths | nindent 10 }}
---