stages:
    - deploy

variables:
  SOURCE_DIR: /source/repos/$CI_PROJECT_NAME

tool-stack.deploy.compose:
  image:
    name: docker/compose:1.25.0
  services:
    - docker:stable-dind
  stage: deploy
  tags:
    - compose
    - tool-stack
  except:
    kubernetes: active
  before_script:
    - apk add make
    - make mongo-backup
  script:
    - make stack
  after_script:
    - make mongo-restore
