project: kicksware
component: elasticsearch
nameOverride: ""
fullnameOverride: ""
baseDirL: &baseDir /run/desktop/mnt/host/wsl

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.9.0
  pullPolicy: IfNotPresent

deployment:
  stateful: false
  serviceName: elasticsearch-
  replicaCount: 1

service:
  type: ClusterIP
  port: 9200
  transportPort: 9300

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: search.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: elasticsearch
          port: 9200
          scheme: http

volumes:
  - name: cert
    host:
      pathBase: *baseDir
      path: /source/cert
      type: Directory
    mountPath: /cert
  - name: backup
    host:
      pathBase: *baseDir
      path: /source/backup/elastic
      type: Directory
    mountPath: /backup


environment: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""