---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-storage
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
  {{- end }}
  hostPath:
    path: {{ .Values.storage.hostPathBase}}{{ .Values.storage.hostPath }}