{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.config }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
