apiVersion: v1
kind: Service
metadata:
  name: gluster-heketi
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}

