global:
  edition: ce

  hosts:
    domain: ci.kicksware.com
    gitlab:
      name: ci.kicksware.com
    registry:
      name: registry.kicksware.com
    minio:
      name: minio.kicksware.com

  ingress:
    enabled: false
    configureCertmanager: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1

  gitaly:
    persistence:
      enabled: true
      size: 25Gi

minio:
  persistence:
    enabled: true
    size: 25Gi

ingress:
  enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

certmanager-issuer:
  email: timothy@kicksware.com

gitlab-runner:
  install: false

prometheus:
  install: false

